package com.hxy.protobuf;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DSFusion.proto

public final class DSFusion {
  private DSFusion() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DSFusionMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional uint32 fusionNum = 1;
    /**
     * <code>optional uint32 fusionNum = 1;</code>
     */
    boolean hasFusionNum();
    /**
     * <code>optional uint32 fusionNum = 1;</code>
     */
    int getFusionNum();

    // optional uint32 mmsi = 2;
    /**
     * <code>optional uint32 mmsi = 2;</code>
     */
    boolean hasMmsi();
    /**
     * <code>optional uint32 mmsi = 2;</code>
     */
    int getMmsi();

    // optional uint32 dynamicUTC = 3;
    /**
     * <code>optional uint32 dynamicUTC = 3;</code>
     */
    boolean hasDynamicUTC();
    /**
     * <code>optional uint32 dynamicUTC = 3;</code>
     */
    int getDynamicUTC();

    // optional double lon = 4;
    /**
     * <code>optional double lon = 4;</code>
     */
    boolean hasLon();
    /**
     * <code>optional double lon = 4;</code>
     */
    double getLon();

    // optional double lat = 5;
    /**
     * <code>optional double lat = 5;</code>
     */
    boolean hasLat();
    /**
     * <code>optional double lat = 5;</code>
     */
    double getLat();

    // optional double course = 7;
    /**
     * <code>optional double course = 7;</code>
     */
    boolean hasCourse();
    /**
     * <code>optional double course = 7;</code>
     */
    double getCourse();

    // optional double speed = 6;
    /**
     * <code>optional double speed = 6;</code>
     */
    boolean hasSpeed();
    /**
     * <code>optional double speed = 6;</code>
     */
    double getSpeed();

    // optional double cSpeed = 8;
    /**
     * <code>optional double cSpeed = 8;</code>
     */
    boolean hasCSpeed();
    /**
     * <code>optional double cSpeed = 8;</code>
     */
    double getCSpeed();

    // optional double cCourse = 9;
    /**
     * <code>optional double cCourse = 9;</code>
     */
    boolean hasCCourse();
    /**
     * <code>optional double cCourse = 9;</code>
     */
    double getCCourse();

    // optional uint32 staticUTC = 10;
    /**
     * <code>optional uint32 staticUTC = 10;</code>
     */
    boolean hasStaticUTC();
    /**
     * <code>optional uint32 staticUTC = 10;</code>
     */
    int getStaticUTC();

    // optional uint32 imo = 11;
    /**
     * <code>optional uint32 imo = 11;</code>
     */
    boolean hasImo();
    /**
     * <code>optional uint32 imo = 11;</code>
     */
    int getImo();

    // optional string callSign = 12;
    /**
     * <code>optional string callSign = 12;</code>
     */
    boolean hasCallSign();
    /**
     * <code>optional string callSign = 12;</code>
     */
    String getCallSign();
    /**
     * <code>optional string callSign = 12;</code>
     */
    com.google.protobuf.ByteString
        getCallSignBytes();

    // optional string shipName = 13;
    /**
     * <code>optional string shipName = 13;</code>
     */
    boolean hasShipName();
    /**
     * <code>optional string shipName = 13;</code>
     */
    String getShipName();
    /**
     * <code>optional string shipName = 13;</code>
     */
    com.google.protobuf.ByteString
        getShipNameBytes();

    // optional uint32 cargoType = 14;
    /**
     * <code>optional uint32 cargoType = 14;</code>
     */
    boolean hasCargoType();
    /**
     * <code>optional uint32 cargoType = 14;</code>
     */
    int getCargoType();

    // optional float shipLength = 15;
    /**
     * <code>optional float shipLength = 15;</code>
     */
    boolean hasShipLength();
    /**
     * <code>optional float shipLength = 15;</code>
     */
    float getShipLength();

    // optional float shipWidth = 16;
    /**
     * <code>optional float shipWidth = 16;</code>
     */
    boolean hasShipWidth();
    /**
     * <code>optional float shipWidth = 16;</code>
     */
    float getShipWidth();

    // optional uint32 locationDeviceType = 17;
    /**
     * <code>optional uint32 locationDeviceType = 17;</code>
     */
    boolean hasLocationDeviceType();
    /**
     * <code>optional uint32 locationDeviceType = 17;</code>
     */
    int getLocationDeviceType();

    // optional string eta = 18;
    /**
     * <code>optional string eta = 18;</code>
     */
    boolean hasEta();
    /**
     * <code>optional string eta = 18;</code>
     */
    String getEta();
    /**
     * <code>optional string eta = 18;</code>
     */
    com.google.protobuf.ByteString
        getEtaBytes();

    // optional float shipDraft = 19;
    /**
     * <code>optional float shipDraft = 19;</code>
     */
    boolean hasShipDraft();
    /**
     * <code>optional float shipDraft = 19;</code>
     */
    float getShipDraft();

    // optional string destination = 20;
    /**
     * <code>optional string destination = 20;</code>
     */
    boolean hasDestination();
    /**
     * <code>optional string destination = 20;</code>
     */
    String getDestination();
    /**
     * <code>optional string destination = 20;</code>
     */
    com.google.protobuf.ByteString
        getDestinationBytes();

    // optional uint32 countryCode = 21;
    /**
     * <code>optional uint32 countryCode = 21;</code>
     */
    boolean hasCountryCode();
    /**
     * <code>optional uint32 countryCode = 21;</code>
     */
    int getCountryCode();

    // optional string recordSource = 22;
    /**
     * <code>optional string recordSource = 22;</code>
     */
    boolean hasRecordSource();
    /**
     * <code>optional string recordSource = 22;</code>
     */
    String getRecordSource();
    /**
     * <code>optional string recordSource = 22;</code>
     */
    com.google.protobuf.ByteString
        getRecordSourceBytes();
  }
  /**
   * Protobuf type {@code DSFusionMessage}
   */
  public static final class DSFusionMessage extends
      com.google.protobuf.GeneratedMessage
      implements DSFusionMessageOrBuilder {
    // Use DSFusionMessage.newBuilder() to construct.
    private DSFusionMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DSFusionMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DSFusionMessage defaultInstance;
    public static DSFusionMessage getDefaultInstance() {
      return defaultInstance;
    }

    public DSFusionMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DSFusionMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              fusionNum_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              mmsi_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              dynamicUTC_ = input.readUInt32();
              break;
            }
            case 33: {
              bitField0_ |= 0x00000008;
              lon_ = input.readDouble();
              break;
            }
            case 41: {
              bitField0_ |= 0x00000010;
              lat_ = input.readDouble();
              break;
            }
            case 49: {
              bitField0_ |= 0x00000040;
              speed_ = input.readDouble();
              break;
            }
            case 57: {
              bitField0_ |= 0x00000020;
              course_ = input.readDouble();
              break;
            }
            case 65: {
              bitField0_ |= 0x00000080;
              cSpeed_ = input.readDouble();
              break;
            }
            case 73: {
              bitField0_ |= 0x00000100;
              cCourse_ = input.readDouble();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              staticUTC_ = input.readUInt32();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000400;
              imo_ = input.readUInt32();
              break;
            }
            case 98: {
              bitField0_ |= 0x00000800;
              callSign_ = input.readBytes();
              break;
            }
            case 106: {
              bitField0_ |= 0x00001000;
              shipName_ = input.readBytes();
              break;
            }
            case 112: {
              bitField0_ |= 0x00002000;
              cargoType_ = input.readUInt32();
              break;
            }
            case 125: {
              bitField0_ |= 0x00004000;
              shipLength_ = input.readFloat();
              break;
            }
            case 133: {
              bitField0_ |= 0x00008000;
              shipWidth_ = input.readFloat();
              break;
            }
            case 136: {
              bitField0_ |= 0x00010000;
              locationDeviceType_ = input.readUInt32();
              break;
            }
            case 146: {
              bitField0_ |= 0x00020000;
              eta_ = input.readBytes();
              break;
            }
            case 157: {
              bitField0_ |= 0x00040000;
              shipDraft_ = input.readFloat();
              break;
            }
            case 162: {
              bitField0_ |= 0x00080000;
              destination_ = input.readBytes();
              break;
            }
            case 168: {
              bitField0_ |= 0x00100000;
              countryCode_ = input.readUInt32();
              break;
            }
            case 178: {
              bitField0_ |= 0x00200000;
              recordSource_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DSFusion.internal_static_DSFusionMessage_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DSFusion.internal_static_DSFusionMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DSFusionMessage.class, Builder.class);
    }

    public static com.google.protobuf.Parser<DSFusionMessage> PARSER =
        new com.google.protobuf.AbstractParser<DSFusionMessage>() {
      public DSFusionMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DSFusionMessage(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<DSFusionMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional uint32 fusionNum = 1;
    public static final int FUSIONNUM_FIELD_NUMBER = 1;
    private int fusionNum_;
    /**
     * <code>optional uint32 fusionNum = 1;</code>
     */
    public boolean hasFusionNum() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint32 fusionNum = 1;</code>
     */
    public int getFusionNum() {
      return fusionNum_;
    }

    // optional uint32 mmsi = 2;
    public static final int MMSI_FIELD_NUMBER = 2;
    private int mmsi_;
    /**
     * <code>optional uint32 mmsi = 2;</code>
     */
    public boolean hasMmsi() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint32 mmsi = 2;</code>
     */
    public int getMmsi() {
      return mmsi_;
    }

    // optional uint32 dynamicUTC = 3;
    public static final int DYNAMICUTC_FIELD_NUMBER = 3;
    private int dynamicUTC_;
    /**
     * <code>optional uint32 dynamicUTC = 3;</code>
     */
    public boolean hasDynamicUTC() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional uint32 dynamicUTC = 3;</code>
     */
    public int getDynamicUTC() {
      return dynamicUTC_;
    }

    // optional double lon = 4;
    public static final int LON_FIELD_NUMBER = 4;
    private double lon_;
    /**
     * <code>optional double lon = 4;</code>
     */
    public boolean hasLon() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional double lon = 4;</code>
     */
    public double getLon() {
      return lon_;
    }

    // optional double lat = 5;
    public static final int LAT_FIELD_NUMBER = 5;
    private double lat_;
    /**
     * <code>optional double lat = 5;</code>
     */
    public boolean hasLat() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional double lat = 5;</code>
     */
    public double getLat() {
      return lat_;
    }

    // optional double course = 7;
    public static final int COURSE_FIELD_NUMBER = 7;
    private double course_;
    /**
     * <code>optional double course = 7;</code>
     */
    public boolean hasCourse() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional double course = 7;</code>
     */
    public double getCourse() {
      return course_;
    }

    // optional double speed = 6;
    public static final int SPEED_FIELD_NUMBER = 6;
    private double speed_;
    /**
     * <code>optional double speed = 6;</code>
     */
    public boolean hasSpeed() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional double speed = 6;</code>
     */
    public double getSpeed() {
      return speed_;
    }

    // optional double cSpeed = 8;
    public static final int CSPEED_FIELD_NUMBER = 8;
    private double cSpeed_;
    /**
     * <code>optional double cSpeed = 8;</code>
     */
    public boolean hasCSpeed() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional double cSpeed = 8;</code>
     */
    public double getCSpeed() {
      return cSpeed_;
    }

    // optional double cCourse = 9;
    public static final int CCOURSE_FIELD_NUMBER = 9;
    private double cCourse_;
    /**
     * <code>optional double cCourse = 9;</code>
     */
    public boolean hasCCourse() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional double cCourse = 9;</code>
     */
    public double getCCourse() {
      return cCourse_;
    }

    // optional uint32 staticUTC = 10;
    public static final int STATICUTC_FIELD_NUMBER = 10;
    private int staticUTC_;
    /**
     * <code>optional uint32 staticUTC = 10;</code>
     */
    public boolean hasStaticUTC() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional uint32 staticUTC = 10;</code>
     */
    public int getStaticUTC() {
      return staticUTC_;
    }

    // optional uint32 imo = 11;
    public static final int IMO_FIELD_NUMBER = 11;
    private int imo_;
    /**
     * <code>optional uint32 imo = 11;</code>
     */
    public boolean hasImo() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional uint32 imo = 11;</code>
     */
    public int getImo() {
      return imo_;
    }

    // optional string callSign = 12;
    public static final int CALLSIGN_FIELD_NUMBER = 12;
    private Object callSign_;
    /**
     * <code>optional string callSign = 12;</code>
     */
    public boolean hasCallSign() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional string callSign = 12;</code>
     */
    public String getCallSign() {
      Object ref = callSign_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          callSign_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string callSign = 12;</code>
     */
    public com.google.protobuf.ByteString
        getCallSignBytes() {
      Object ref = callSign_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        callSign_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string shipName = 13;
    public static final int SHIPNAME_FIELD_NUMBER = 13;
    private Object shipName_;
    /**
     * <code>optional string shipName = 13;</code>
     */
    public boolean hasShipName() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>optional string shipName = 13;</code>
     */
    public String getShipName() {
      Object ref = shipName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          shipName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string shipName = 13;</code>
     */
    public com.google.protobuf.ByteString
        getShipNameBytes() {
      Object ref = shipName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        shipName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional uint32 cargoType = 14;
    public static final int CARGOTYPE_FIELD_NUMBER = 14;
    private int cargoType_;
    /**
     * <code>optional uint32 cargoType = 14;</code>
     */
    public boolean hasCargoType() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    /**
     * <code>optional uint32 cargoType = 14;</code>
     */
    public int getCargoType() {
      return cargoType_;
    }

    // optional float shipLength = 15;
    public static final int SHIPLENGTH_FIELD_NUMBER = 15;
    private float shipLength_;
    /**
     * <code>optional float shipLength = 15;</code>
     */
    public boolean hasShipLength() {
      return ((bitField0_ & 0x00004000) == 0x00004000);
    }
    /**
     * <code>optional float shipLength = 15;</code>
     */
    public float getShipLength() {
      return shipLength_;
    }

    // optional float shipWidth = 16;
    public static final int SHIPWIDTH_FIELD_NUMBER = 16;
    private float shipWidth_;
    /**
     * <code>optional float shipWidth = 16;</code>
     */
    public boolean hasShipWidth() {
      return ((bitField0_ & 0x00008000) == 0x00008000);
    }
    /**
     * <code>optional float shipWidth = 16;</code>
     */
    public float getShipWidth() {
      return shipWidth_;
    }

    // optional uint32 locationDeviceType = 17;
    public static final int LOCATIONDEVICETYPE_FIELD_NUMBER = 17;
    private int locationDeviceType_;
    /**
     * <code>optional uint32 locationDeviceType = 17;</code>
     */
    public boolean hasLocationDeviceType() {
      return ((bitField0_ & 0x00010000) == 0x00010000);
    }
    /**
     * <code>optional uint32 locationDeviceType = 17;</code>
     */
    public int getLocationDeviceType() {
      return locationDeviceType_;
    }

    // optional string eta = 18;
    public static final int ETA_FIELD_NUMBER = 18;
    private Object eta_;
    /**
     * <code>optional string eta = 18;</code>
     */
    public boolean hasEta() {
      return ((bitField0_ & 0x00020000) == 0x00020000);
    }
    /**
     * <code>optional string eta = 18;</code>
     */
    public String getEta() {
      Object ref = eta_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          eta_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string eta = 18;</code>
     */
    public com.google.protobuf.ByteString
        getEtaBytes() {
      Object ref = eta_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        eta_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional float shipDraft = 19;
    public static final int SHIPDRAFT_FIELD_NUMBER = 19;
    private float shipDraft_;
    /**
     * <code>optional float shipDraft = 19;</code>
     */
    public boolean hasShipDraft() {
      return ((bitField0_ & 0x00040000) == 0x00040000);
    }
    /**
     * <code>optional float shipDraft = 19;</code>
     */
    public float getShipDraft() {
      return shipDraft_;
    }

    // optional string destination = 20;
    public static final int DESTINATION_FIELD_NUMBER = 20;
    private Object destination_;
    /**
     * <code>optional string destination = 20;</code>
     */
    public boolean hasDestination() {
      return ((bitField0_ & 0x00080000) == 0x00080000);
    }
    /**
     * <code>optional string destination = 20;</code>
     */
    public String getDestination() {
      Object ref = destination_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          destination_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string destination = 20;</code>
     */
    public com.google.protobuf.ByteString
        getDestinationBytes() {
      Object ref = destination_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        destination_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional uint32 countryCode = 21;
    public static final int COUNTRYCODE_FIELD_NUMBER = 21;
    private int countryCode_;
    /**
     * <code>optional uint32 countryCode = 21;</code>
     */
    public boolean hasCountryCode() {
      return ((bitField0_ & 0x00100000) == 0x00100000);
    }
    /**
     * <code>optional uint32 countryCode = 21;</code>
     */
    public int getCountryCode() {
      return countryCode_;
    }

    // optional string recordSource = 22;
    public static final int RECORDSOURCE_FIELD_NUMBER = 22;
    private Object recordSource_;
    /**
     * <code>optional string recordSource = 22;</code>
     */
    public boolean hasRecordSource() {
      return ((bitField0_ & 0x00200000) == 0x00200000);
    }
    /**
     * <code>optional string recordSource = 22;</code>
     */
    public String getRecordSource() {
      Object ref = recordSource_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          recordSource_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string recordSource = 22;</code>
     */
    public com.google.protobuf.ByteString
        getRecordSourceBytes() {
      Object ref = recordSource_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        recordSource_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      fusionNum_ = 0;
      mmsi_ = 0;
      dynamicUTC_ = 0;
      lon_ = 0D;
      lat_ = 0D;
      course_ = 0D;
      speed_ = 0D;
      cSpeed_ = 0D;
      cCourse_ = 0D;
      staticUTC_ = 0;
      imo_ = 0;
      callSign_ = "";
      shipName_ = "";
      cargoType_ = 0;
      shipLength_ = 0F;
      shipWidth_ = 0F;
      locationDeviceType_ = 0;
      eta_ = "";
      shipDraft_ = 0F;
      destination_ = "";
      countryCode_ = 0;
      recordSource_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, fusionNum_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, mmsi_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, dynamicUTC_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeDouble(4, lon_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeDouble(5, lat_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeDouble(6, speed_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeDouble(7, course_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeDouble(8, cSpeed_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeDouble(9, cCourse_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeUInt32(10, staticUTC_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeUInt32(11, imo_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeBytes(12, getCallSignBytes());
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeBytes(13, getShipNameBytes());
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeUInt32(14, cargoType_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        output.writeFloat(15, shipLength_);
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        output.writeFloat(16, shipWidth_);
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        output.writeUInt32(17, locationDeviceType_);
      }
      if (((bitField0_ & 0x00020000) == 0x00020000)) {
        output.writeBytes(18, getEtaBytes());
      }
      if (((bitField0_ & 0x00040000) == 0x00040000)) {
        output.writeFloat(19, shipDraft_);
      }
      if (((bitField0_ & 0x00080000) == 0x00080000)) {
        output.writeBytes(20, getDestinationBytes());
      }
      if (((bitField0_ & 0x00100000) == 0x00100000)) {
        output.writeUInt32(21, countryCode_);
      }
      if (((bitField0_ & 0x00200000) == 0x00200000)) {
        output.writeBytes(22, getRecordSourceBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, fusionNum_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, mmsi_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, dynamicUTC_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, lon_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, lat_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, speed_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(7, course_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(8, cSpeed_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(9, cCourse_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(10, staticUTC_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(11, imo_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(12, getCallSignBytes());
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(13, getShipNameBytes());
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(14, cargoType_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(15, shipLength_);
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(16, shipWidth_);
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(17, locationDeviceType_);
      }
      if (((bitField0_ & 0x00020000) == 0x00020000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(18, getEtaBytes());
      }
      if (((bitField0_ & 0x00040000) == 0x00040000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(19, shipDraft_);
      }
      if (((bitField0_ & 0x00080000) == 0x00080000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(20, getDestinationBytes());
      }
      if (((bitField0_ & 0x00100000) == 0x00100000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(21, countryCode_);
      }
      if (((bitField0_ & 0x00200000) == 0x00200000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(22, getRecordSourceBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static DSFusionMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DSFusionMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DSFusionMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DSFusionMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DSFusionMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static DSFusionMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static DSFusionMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static DSFusionMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static DSFusionMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static DSFusionMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(DSFusionMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DSFusionMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements DSFusionMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DSFusion.internal_static_DSFusionMessage_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DSFusion.internal_static_DSFusionMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DSFusionMessage.class, Builder.class);
      }

      // Construct using DSFusion.DSFusionMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        fusionNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        mmsi_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        dynamicUTC_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        lon_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000008);
        lat_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000010);
        course_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000020);
        speed_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000040);
        cSpeed_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000080);
        cCourse_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000100);
        staticUTC_ = 0;
        bitField0_ = (bitField0_ & ~0x00000200);
        imo_ = 0;
        bitField0_ = (bitField0_ & ~0x00000400);
        callSign_ = "";
        bitField0_ = (bitField0_ & ~0x00000800);
        shipName_ = "";
        bitField0_ = (bitField0_ & ~0x00001000);
        cargoType_ = 0;
        bitField0_ = (bitField0_ & ~0x00002000);
        shipLength_ = 0F;
        bitField0_ = (bitField0_ & ~0x00004000);
        shipWidth_ = 0F;
        bitField0_ = (bitField0_ & ~0x00008000);
        locationDeviceType_ = 0;
        bitField0_ = (bitField0_ & ~0x00010000);
        eta_ = "";
        bitField0_ = (bitField0_ & ~0x00020000);
        shipDraft_ = 0F;
        bitField0_ = (bitField0_ & ~0x00040000);
        destination_ = "";
        bitField0_ = (bitField0_ & ~0x00080000);
        countryCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00100000);
        recordSource_ = "";
        bitField0_ = (bitField0_ & ~0x00200000);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DSFusion.internal_static_DSFusionMessage_descriptor;
      }

      public DSFusionMessage getDefaultInstanceForType() {
        return DSFusionMessage.getDefaultInstance();
      }

      public DSFusionMessage build() {
        DSFusionMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public DSFusionMessage buildPartial() {
        DSFusionMessage result = new DSFusionMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.fusionNum_ = fusionNum_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.mmsi_ = mmsi_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.dynamicUTC_ = dynamicUTC_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.lon_ = lon_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.lat_ = lat_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.course_ = course_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.speed_ = speed_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.cSpeed_ = cSpeed_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.cCourse_ = cCourse_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.staticUTC_ = staticUTC_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.imo_ = imo_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.callSign_ = callSign_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.shipName_ = shipName_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.cargoType_ = cargoType_;
        if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
          to_bitField0_ |= 0x00004000;
        }
        result.shipLength_ = shipLength_;
        if (((from_bitField0_ & 0x00008000) == 0x00008000)) {
          to_bitField0_ |= 0x00008000;
        }
        result.shipWidth_ = shipWidth_;
        if (((from_bitField0_ & 0x00010000) == 0x00010000)) {
          to_bitField0_ |= 0x00010000;
        }
        result.locationDeviceType_ = locationDeviceType_;
        if (((from_bitField0_ & 0x00020000) == 0x00020000)) {
          to_bitField0_ |= 0x00020000;
        }
        result.eta_ = eta_;
        if (((from_bitField0_ & 0x00040000) == 0x00040000)) {
          to_bitField0_ |= 0x00040000;
        }
        result.shipDraft_ = shipDraft_;
        if (((from_bitField0_ & 0x00080000) == 0x00080000)) {
          to_bitField0_ |= 0x00080000;
        }
        result.destination_ = destination_;
        if (((from_bitField0_ & 0x00100000) == 0x00100000)) {
          to_bitField0_ |= 0x00100000;
        }
        result.countryCode_ = countryCode_;
        if (((from_bitField0_ & 0x00200000) == 0x00200000)) {
          to_bitField0_ |= 0x00200000;
        }
        result.recordSource_ = recordSource_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DSFusionMessage) {
          return mergeFrom((DSFusionMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DSFusionMessage other) {
        if (other == DSFusionMessage.getDefaultInstance()) return this;
        if (other.hasFusionNum()) {
          setFusionNum(other.getFusionNum());
        }
        if (other.hasMmsi()) {
          setMmsi(other.getMmsi());
        }
        if (other.hasDynamicUTC()) {
          setDynamicUTC(other.getDynamicUTC());
        }
        if (other.hasLon()) {
          setLon(other.getLon());
        }
        if (other.hasLat()) {
          setLat(other.getLat());
        }
        if (other.hasCourse()) {
          setCourse(other.getCourse());
        }
        if (other.hasSpeed()) {
          setSpeed(other.getSpeed());
        }
        if (other.hasCSpeed()) {
          setCSpeed(other.getCSpeed());
        }
        if (other.hasCCourse()) {
          setCCourse(other.getCCourse());
        }
        if (other.hasStaticUTC()) {
          setStaticUTC(other.getStaticUTC());
        }
        if (other.hasImo()) {
          setImo(other.getImo());
        }
        if (other.hasCallSign()) {
          bitField0_ |= 0x00000800;
          callSign_ = other.callSign_;
          onChanged();
        }
        if (other.hasShipName()) {
          bitField0_ |= 0x00001000;
          shipName_ = other.shipName_;
          onChanged();
        }
        if (other.hasCargoType()) {
          setCargoType(other.getCargoType());
        }
        if (other.hasShipLength()) {
          setShipLength(other.getShipLength());
        }
        if (other.hasShipWidth()) {
          setShipWidth(other.getShipWidth());
        }
        if (other.hasLocationDeviceType()) {
          setLocationDeviceType(other.getLocationDeviceType());
        }
        if (other.hasEta()) {
          bitField0_ |= 0x00020000;
          eta_ = other.eta_;
          onChanged();
        }
        if (other.hasShipDraft()) {
          setShipDraft(other.getShipDraft());
        }
        if (other.hasDestination()) {
          bitField0_ |= 0x00080000;
          destination_ = other.destination_;
          onChanged();
        }
        if (other.hasCountryCode()) {
          setCountryCode(other.getCountryCode());
        }
        if (other.hasRecordSource()) {
          bitField0_ |= 0x00200000;
          recordSource_ = other.recordSource_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        DSFusionMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DSFusionMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional uint32 fusionNum = 1;
      private int fusionNum_ ;
      /**
       * <code>optional uint32 fusionNum = 1;</code>
       */
      public boolean hasFusionNum() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint32 fusionNum = 1;</code>
       */
      public int getFusionNum() {
        return fusionNum_;
      }
      /**
       * <code>optional uint32 fusionNum = 1;</code>
       */
      public Builder setFusionNum(int value) {
        bitField0_ |= 0x00000001;
        fusionNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 fusionNum = 1;</code>
       */
      public Builder clearFusionNum() {
        bitField0_ = (bitField0_ & ~0x00000001);
        fusionNum_ = 0;
        onChanged();
        return this;
      }

      // optional uint32 mmsi = 2;
      private int mmsi_ ;
      /**
       * <code>optional uint32 mmsi = 2;</code>
       */
      public boolean hasMmsi() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint32 mmsi = 2;</code>
       */
      public int getMmsi() {
        return mmsi_;
      }
      /**
       * <code>optional uint32 mmsi = 2;</code>
       */
      public Builder setMmsi(int value) {
        bitField0_ |= 0x00000002;
        mmsi_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 mmsi = 2;</code>
       */
      public Builder clearMmsi() {
        bitField0_ = (bitField0_ & ~0x00000002);
        mmsi_ = 0;
        onChanged();
        return this;
      }

      // optional uint32 dynamicUTC = 3;
      private int dynamicUTC_ ;
      /**
       * <code>optional uint32 dynamicUTC = 3;</code>
       */
      public boolean hasDynamicUTC() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional uint32 dynamicUTC = 3;</code>
       */
      public int getDynamicUTC() {
        return dynamicUTC_;
      }
      /**
       * <code>optional uint32 dynamicUTC = 3;</code>
       */
      public Builder setDynamicUTC(int value) {
        bitField0_ |= 0x00000004;
        dynamicUTC_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 dynamicUTC = 3;</code>
       */
      public Builder clearDynamicUTC() {
        bitField0_ = (bitField0_ & ~0x00000004);
        dynamicUTC_ = 0;
        onChanged();
        return this;
      }

      // optional double lon = 4;
      private double lon_ ;
      /**
       * <code>optional double lon = 4;</code>
       */
      public boolean hasLon() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional double lon = 4;</code>
       */
      public double getLon() {
        return lon_;
      }
      /**
       * <code>optional double lon = 4;</code>
       */
      public Builder setLon(double value) {
        bitField0_ |= 0x00000008;
        lon_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double lon = 4;</code>
       */
      public Builder clearLon() {
        bitField0_ = (bitField0_ & ~0x00000008);
        lon_ = 0D;
        onChanged();
        return this;
      }

      // optional double lat = 5;
      private double lat_ ;
      /**
       * <code>optional double lat = 5;</code>
       */
      public boolean hasLat() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional double lat = 5;</code>
       */
      public double getLat() {
        return lat_;
      }
      /**
       * <code>optional double lat = 5;</code>
       */
      public Builder setLat(double value) {
        bitField0_ |= 0x00000010;
        lat_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double lat = 5;</code>
       */
      public Builder clearLat() {
        bitField0_ = (bitField0_ & ~0x00000010);
        lat_ = 0D;
        onChanged();
        return this;
      }

      // optional double course = 7;
      private double course_ ;
      /**
       * <code>optional double course = 7;</code>
       */
      public boolean hasCourse() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional double course = 7;</code>
       */
      public double getCourse() {
        return course_;
      }
      /**
       * <code>optional double course = 7;</code>
       */
      public Builder setCourse(double value) {
        bitField0_ |= 0x00000020;
        course_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double course = 7;</code>
       */
      public Builder clearCourse() {
        bitField0_ = (bitField0_ & ~0x00000020);
        course_ = 0D;
        onChanged();
        return this;
      }

      // optional double speed = 6;
      private double speed_ ;
      /**
       * <code>optional double speed = 6;</code>
       */
      public boolean hasSpeed() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional double speed = 6;</code>
       */
      public double getSpeed() {
        return speed_;
      }
      /**
       * <code>optional double speed = 6;</code>
       */
      public Builder setSpeed(double value) {
        bitField0_ |= 0x00000040;
        speed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double speed = 6;</code>
       */
      public Builder clearSpeed() {
        bitField0_ = (bitField0_ & ~0x00000040);
        speed_ = 0D;
        onChanged();
        return this;
      }

      // optional double cSpeed = 8;
      private double cSpeed_ ;
      /**
       * <code>optional double cSpeed = 8;</code>
       */
      public boolean hasCSpeed() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional double cSpeed = 8;</code>
       */
      public double getCSpeed() {
        return cSpeed_;
      }
      /**
       * <code>optional double cSpeed = 8;</code>
       */
      public Builder setCSpeed(double value) {
        bitField0_ |= 0x00000080;
        cSpeed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double cSpeed = 8;</code>
       */
      public Builder clearCSpeed() {
        bitField0_ = (bitField0_ & ~0x00000080);
        cSpeed_ = 0D;
        onChanged();
        return this;
      }

      // optional double cCourse = 9;
      private double cCourse_ ;
      /**
       * <code>optional double cCourse = 9;</code>
       */
      public boolean hasCCourse() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional double cCourse = 9;</code>
       */
      public double getCCourse() {
        return cCourse_;
      }
      /**
       * <code>optional double cCourse = 9;</code>
       */
      public Builder setCCourse(double value) {
        bitField0_ |= 0x00000100;
        cCourse_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double cCourse = 9;</code>
       */
      public Builder clearCCourse() {
        bitField0_ = (bitField0_ & ~0x00000100);
        cCourse_ = 0D;
        onChanged();
        return this;
      }

      // optional uint32 staticUTC = 10;
      private int staticUTC_ ;
      /**
       * <code>optional uint32 staticUTC = 10;</code>
       */
      public boolean hasStaticUTC() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional uint32 staticUTC = 10;</code>
       */
      public int getStaticUTC() {
        return staticUTC_;
      }
      /**
       * <code>optional uint32 staticUTC = 10;</code>
       */
      public Builder setStaticUTC(int value) {
        bitField0_ |= 0x00000200;
        staticUTC_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 staticUTC = 10;</code>
       */
      public Builder clearStaticUTC() {
        bitField0_ = (bitField0_ & ~0x00000200);
        staticUTC_ = 0;
        onChanged();
        return this;
      }

      // optional uint32 imo = 11;
      private int imo_ ;
      /**
       * <code>optional uint32 imo = 11;</code>
       */
      public boolean hasImo() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional uint32 imo = 11;</code>
       */
      public int getImo() {
        return imo_;
      }
      /**
       * <code>optional uint32 imo = 11;</code>
       */
      public Builder setImo(int value) {
        bitField0_ |= 0x00000400;
        imo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 imo = 11;</code>
       */
      public Builder clearImo() {
        bitField0_ = (bitField0_ & ~0x00000400);
        imo_ = 0;
        onChanged();
        return this;
      }

      // optional string callSign = 12;
      private Object callSign_ = "";
      /**
       * <code>optional string callSign = 12;</code>
       */
      public boolean hasCallSign() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional string callSign = 12;</code>
       */
      public String getCallSign() {
        Object ref = callSign_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          callSign_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string callSign = 12;</code>
       */
      public com.google.protobuf.ByteString
          getCallSignBytes() {
        Object ref = callSign_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          callSign_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string callSign = 12;</code>
       */
      public Builder setCallSign(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        callSign_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string callSign = 12;</code>
       */
      public Builder clearCallSign() {
        bitField0_ = (bitField0_ & ~0x00000800);
        callSign_ = getDefaultInstance().getCallSign();
        onChanged();
        return this;
      }
      /**
       * <code>optional string callSign = 12;</code>
       */
      public Builder setCallSignBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        callSign_ = value;
        onChanged();
        return this;
      }

      // optional string shipName = 13;
      private Object shipName_ = "";
      /**
       * <code>optional string shipName = 13;</code>
       */
      public boolean hasShipName() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>optional string shipName = 13;</code>
       */
      public String getShipName() {
        Object ref = shipName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          shipName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string shipName = 13;</code>
       */
      public com.google.protobuf.ByteString
          getShipNameBytes() {
        Object ref = shipName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          shipName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string shipName = 13;</code>
       */
      public Builder setShipName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
        shipName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string shipName = 13;</code>
       */
      public Builder clearShipName() {
        bitField0_ = (bitField0_ & ~0x00001000);
        shipName_ = getDefaultInstance().getShipName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string shipName = 13;</code>
       */
      public Builder setShipNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
        shipName_ = value;
        onChanged();
        return this;
      }

      // optional uint32 cargoType = 14;
      private int cargoType_ ;
      /**
       * <code>optional uint32 cargoType = 14;</code>
       */
      public boolean hasCargoType() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      /**
       * <code>optional uint32 cargoType = 14;</code>
       */
      public int getCargoType() {
        return cargoType_;
      }
      /**
       * <code>optional uint32 cargoType = 14;</code>
       */
      public Builder setCargoType(int value) {
        bitField0_ |= 0x00002000;
        cargoType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 cargoType = 14;</code>
       */
      public Builder clearCargoType() {
        bitField0_ = (bitField0_ & ~0x00002000);
        cargoType_ = 0;
        onChanged();
        return this;
      }

      // optional float shipLength = 15;
      private float shipLength_ ;
      /**
       * <code>optional float shipLength = 15;</code>
       */
      public boolean hasShipLength() {
        return ((bitField0_ & 0x00004000) == 0x00004000);
      }
      /**
       * <code>optional float shipLength = 15;</code>
       */
      public float getShipLength() {
        return shipLength_;
      }
      /**
       * <code>optional float shipLength = 15;</code>
       */
      public Builder setShipLength(float value) {
        bitField0_ |= 0x00004000;
        shipLength_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float shipLength = 15;</code>
       */
      public Builder clearShipLength() {
        bitField0_ = (bitField0_ & ~0x00004000);
        shipLength_ = 0F;
        onChanged();
        return this;
      }

      // optional float shipWidth = 16;
      private float shipWidth_ ;
      /**
       * <code>optional float shipWidth = 16;</code>
       */
      public boolean hasShipWidth() {
        return ((bitField0_ & 0x00008000) == 0x00008000);
      }
      /**
       * <code>optional float shipWidth = 16;</code>
       */
      public float getShipWidth() {
        return shipWidth_;
      }
      /**
       * <code>optional float shipWidth = 16;</code>
       */
      public Builder setShipWidth(float value) {
        bitField0_ |= 0x00008000;
        shipWidth_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float shipWidth = 16;</code>
       */
      public Builder clearShipWidth() {
        bitField0_ = (bitField0_ & ~0x00008000);
        shipWidth_ = 0F;
        onChanged();
        return this;
      }

      // optional uint32 locationDeviceType = 17;
      private int locationDeviceType_ ;
      /**
       * <code>optional uint32 locationDeviceType = 17;</code>
       */
      public boolean hasLocationDeviceType() {
        return ((bitField0_ & 0x00010000) == 0x00010000);
      }
      /**
       * <code>optional uint32 locationDeviceType = 17;</code>
       */
      public int getLocationDeviceType() {
        return locationDeviceType_;
      }
      /**
       * <code>optional uint32 locationDeviceType = 17;</code>
       */
      public Builder setLocationDeviceType(int value) {
        bitField0_ |= 0x00010000;
        locationDeviceType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 locationDeviceType = 17;</code>
       */
      public Builder clearLocationDeviceType() {
        bitField0_ = (bitField0_ & ~0x00010000);
        locationDeviceType_ = 0;
        onChanged();
        return this;
      }

      // optional string eta = 18;
      private Object eta_ = "";
      /**
       * <code>optional string eta = 18;</code>
       */
      public boolean hasEta() {
        return ((bitField0_ & 0x00020000) == 0x00020000);
      }
      /**
       * <code>optional string eta = 18;</code>
       */
      public String getEta() {
        Object ref = eta_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          eta_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string eta = 18;</code>
       */
      public com.google.protobuf.ByteString
          getEtaBytes() {
        Object ref = eta_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          eta_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string eta = 18;</code>
       */
      public Builder setEta(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00020000;
        eta_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string eta = 18;</code>
       */
      public Builder clearEta() {
        bitField0_ = (bitField0_ & ~0x00020000);
        eta_ = getDefaultInstance().getEta();
        onChanged();
        return this;
      }
      /**
       * <code>optional string eta = 18;</code>
       */
      public Builder setEtaBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00020000;
        eta_ = value;
        onChanged();
        return this;
      }

      // optional float shipDraft = 19;
      private float shipDraft_ ;
      /**
       * <code>optional float shipDraft = 19;</code>
       */
      public boolean hasShipDraft() {
        return ((bitField0_ & 0x00040000) == 0x00040000);
      }
      /**
       * <code>optional float shipDraft = 19;</code>
       */
      public float getShipDraft() {
        return shipDraft_;
      }
      /**
       * <code>optional float shipDraft = 19;</code>
       */
      public Builder setShipDraft(float value) {
        bitField0_ |= 0x00040000;
        shipDraft_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float shipDraft = 19;</code>
       */
      public Builder clearShipDraft() {
        bitField0_ = (bitField0_ & ~0x00040000);
        shipDraft_ = 0F;
        onChanged();
        return this;
      }

      // optional string destination = 20;
      private Object destination_ = "";
      /**
       * <code>optional string destination = 20;</code>
       */
      public boolean hasDestination() {
        return ((bitField0_ & 0x00080000) == 0x00080000);
      }
      /**
       * <code>optional string destination = 20;</code>
       */
      public String getDestination() {
        Object ref = destination_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          destination_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string destination = 20;</code>
       */
      public com.google.protobuf.ByteString
          getDestinationBytes() {
        Object ref = destination_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          destination_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string destination = 20;</code>
       */
      public Builder setDestination(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00080000;
        destination_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string destination = 20;</code>
       */
      public Builder clearDestination() {
        bitField0_ = (bitField0_ & ~0x00080000);
        destination_ = getDefaultInstance().getDestination();
        onChanged();
        return this;
      }
      /**
       * <code>optional string destination = 20;</code>
       */
      public Builder setDestinationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00080000;
        destination_ = value;
        onChanged();
        return this;
      }

      // optional uint32 countryCode = 21;
      private int countryCode_ ;
      /**
       * <code>optional uint32 countryCode = 21;</code>
       */
      public boolean hasCountryCode() {
        return ((bitField0_ & 0x00100000) == 0x00100000);
      }
      /**
       * <code>optional uint32 countryCode = 21;</code>
       */
      public int getCountryCode() {
        return countryCode_;
      }
      /**
       * <code>optional uint32 countryCode = 21;</code>
       */
      public Builder setCountryCode(int value) {
        bitField0_ |= 0x00100000;
        countryCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 countryCode = 21;</code>
       */
      public Builder clearCountryCode() {
        bitField0_ = (bitField0_ & ~0x00100000);
        countryCode_ = 0;
        onChanged();
        return this;
      }

      // optional string recordSource = 22;
      private Object recordSource_ = "";
      /**
       * <code>optional string recordSource = 22;</code>
       */
      public boolean hasRecordSource() {
        return ((bitField0_ & 0x00200000) == 0x00200000);
      }
      /**
       * <code>optional string recordSource = 22;</code>
       */
      public String getRecordSource() {
        Object ref = recordSource_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          recordSource_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string recordSource = 22;</code>
       */
      public com.google.protobuf.ByteString
          getRecordSourceBytes() {
        Object ref = recordSource_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          recordSource_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string recordSource = 22;</code>
       */
      public Builder setRecordSource(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00200000;
        recordSource_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string recordSource = 22;</code>
       */
      public Builder clearRecordSource() {
        bitField0_ = (bitField0_ & ~0x00200000);
        recordSource_ = getDefaultInstance().getRecordSource();
        onChanged();
        return this;
      }
      /**
       * <code>optional string recordSource = 22;</code>
       */
      public Builder setRecordSourceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00200000;
        recordSource_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:DSFusionMessage)
    }

    static {
      defaultInstance = new DSFusionMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:DSFusionMessage)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_DSFusionMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_DSFusionMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016DSFusion.proto\"\232\003\n\017DSFusionMessage\022\021\n\t" +
      "fusionNum\030\001 \001(\r\022\014\n\004mmsi\030\002 \001(\r\022\022\n\ndynamic" +
      "UTC\030\003 \001(\r\022\013\n\003lon\030\004 \001(\001\022\013\n\003lat\030\005 \001(\001\022\016\n\006c" +
      "ourse\030\007 \001(\001\022\r\n\005speed\030\006 \001(\001\022\016\n\006cSpeed\030\010 \001" +
      "(\001\022\017\n\007cCourse\030\t \001(\001\022\021\n\tstaticUTC\030\n \001(\r\022\013" +
      "\n\003imo\030\013 \001(\r\022\020\n\010callSign\030\014 \001(\t\022\020\n\010shipNam" +
      "e\030\r \001(\t\022\021\n\tcargoType\030\016 \001(\r\022\022\n\nshipLength" +
      "\030\017 \001(\002\022\021\n\tshipWidth\030\020 \001(\002\022\032\n\022locationDev" +
      "iceType\030\021 \001(\r\022\013\n\003eta\030\022 \001(\t\022\021\n\tshipDraft\030" +
      "\023 \001(\002\022\023\n\013destination\030\024 \001(\t\022\023\n\013countryCod",
      "e\030\025 \001(\r\022\024\n\014recordSource\030\026 \001(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_DSFusionMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_DSFusionMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_DSFusionMessage_descriptor,
              new String[] { "FusionNum", "Mmsi", "DynamicUTC", "Lon", "Lat", "Course", "Speed", "CSpeed", "CCourse", "StaticUTC", "Imo", "CallSign", "ShipName", "CargoType", "ShipLength", "ShipWidth", "LocationDeviceType", "Eta", "ShipDraft", "Destination", "CountryCode", "RecordSource", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
